### ISSUE TITLE
Bootcamp Feedback TODO

### ISSUE THREAD

**Issue by NaraSakamoto** [belatenorio/SAP011-guess-the-number#2]
Isa, 

Deixo aqui algumas sugestões para você continuar a sua jornada de estudos! 

Para continuar se aprimorando como Desenvolvedora Backend Java, sugiro se aprofundar em: 
- [ ] Linguagem Java e para isso deixo algumas sugestões de estudo prático de Java para você escolher: 
   - [ ] [exercism](https://exercism.org/tracks/java)
   - [ ] [Code Academy](https://www.codecademy.com/learn/learn-java)
   - [ ] [Hacker Rank](https://www.hackerrank.com/domains/java)

- [ ] Conceitos de Programação Orientada a Objetos. Sugiro alguns cursos gratuitos, escolha um para fazer: 
   - [ ] [Fundação Bradesco](https://www.ev.org.br/cursos/introducao-a-programacao-orientada-a-objetos-poo)
   - [ ] [Dev Dojo - Maratona Java](https://youtu.be/VKjFuX91G5Q?feature=shared)
   
- [ ] Se aprofundar na construção de APIs REST usando Spring Boot. Sugiro alguns cursos gratuitos como: 
   - [ ] [Spring Boot 3 | Complete Course 2023](https://www.youtube.com/watch?v=wlYvA2b1BWI)
   - [ ] [Desafio Vagas: API de tarefas com Spring Boot!](https://www.youtube.com/watch?v=IjProDV001o)
   - [ ] [Dev Dojo - Spring Boot Essentials 2](https://youtube.com/playlist?list=PL62G310vn6nFBIxp6ZwGnm8xMcGE3VA5H&feature=shared)

Revisando os seus Objetivos de Aprendizagem de cada um dos projetos da Laboratória, deixo aqui algumas sugestões de estudos que podem complementar o seu aprendizado. 

Sobre Firestore: 
- [ ] Você pode criar um site que armazene uma lista de tarefas e armazenálas no firestore. Conteúdo que pode ser útil: [Introdução ao Firestore](https://www.youtube.com/watch?v=DuIOsh1WL5Y)

Sobre Callbacks e Promesas em JavaScript: 
- [ ] Você pode fazer alguns exercícios do freeCodeCamp: 
   - [ ] [Criando uma promise](https://www.freecodecamp.org/portuguese/learn/javascript-algorithms-and-data-structures/es6/create-a-javascript-promise)
   - [ ] [Complete a promise com resolve e reject](https://www.freecodecamp.org/portuguese/learn/javascript-algorithms-and-data-structures/es6/complete-a-promise-with-resolve-and-reject)
   - [ ] [Promise com then](https://www.freecodecamp.org/portuguese/learn/javascript-algorithms-and-data-structures/es6/handle-a-fulfilled-promise-with-then)
   - [ ] [Promise com catch](https://www.freecodecamp.org/portuguese/learn/javascript-algorithms-and-data-structures/es6/handle-a-rejected-promise-with-catch)
   
 
 Parabéns pela sua jornada ao longo do Bootcamp, Isa! Você aproveitou bastante todas as oportunidades de aprendizagem!
 Foi só o começo da sua carreira de sucesso na Tecnologia! 
 
 Beijos!
